### ISSUE TITLE
yarn issue

### ISSUE THREAD

**Issue by kmchen** [do82/rock-paper-scissors-game#1]
Hi @do82 ,

i executed `yarn install --frozen-lockfile` as shown in the readme and getting following error.

Node version: v16.13.0
OS: MacOS 11.0.1

<img width="1098" alt="Screen Shot 2022-02-01 at 5 33 54 PM" src="https://user-images.githubusercontent.com/697297/152012053-3b47e8de-32e7-47ac-a4da-3a9850bf3718.png">

**Comment by do82** [comment]
Closed with https://github.com/do82/rock-paper-scissors-game/commit/7f76a9acf0bbe3ed1be90878542e53bb80cfae2a
